# Generated by Django 5.2.8 on 2025-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0003_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.TextField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="normal",
                verbose_name="Priority",
            ),
        ),
    ]
