# Generated by Django 5.2.8 on 2025-11-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
