# Generated by Django 5.2.8 on 2025-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0006_alter_task_options_remove_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Deadline"),
        ),
    ]
