# Generated by Django 5.2.8 on 2025-12-09 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0007_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("completed", "-priority"),
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
